<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Promise.prototype.then</title>
  </head>
  <body>
    <script>
      // 创建 promise 对象
      const p = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve("用户数据");
          // reject("出错啦");
        }, 1000);
      });

      // 调用 then 方法  then方法的返回结果是 Promise 对象, 对象状态由回调函数的执行结果决定

      // --------------------- 普通调用方式 ---------------------
      // Promise的成功或者失败状态为"fulfilled"；默认返回值为：undefined
      const result = p.then(
        (value) => {
          console.log(value);
        },
        (reason) => {
          console.warn(reason);
        }
      );
      // 控制台输出：Promise {<pending>}</br> __proto__: Promise </br>[[PromiseState]]: "fulfilled" </br>[[PromiseResult]]: undefined
      console.log(result);

      // 回调结果返回自定义成功或者失败状态
      // 有三种类型情况：1）非 promise 类型的属性；2）是 promise 对象；3）抛出错误
      // 1）. 非 promise 类型的属性
      const result1 = p.then(
        (value) => {
          console.log(value);
          // 成功返回：Hello, Promise!
          return "Hello, Promise!";
        },
        (reason) => {
          console.warn(reason);
        }
      );
      // 控制台输出：[[PromiseResult]]: "Hello, Promise!"，其他不变。
      console.log(result1);

      // 2）. 是 promise 对象
      const result2 = p.then(
        (value) => {
          console.log(value);
          return new Promise((resolve, reject) => {
            // 内层回调成功时输出
            resolve("ok");
            // 内层回调失败时输出
            reject("error");
          });
        },
        (reason) => {
          console.warn(reason);
        }
      );
      // 控制台输出：成功时，[[PromiseResult]]: "ok"，其他不变；失败时，[[PromiseState]]: "rejected"，[[PromiseResult]]: "error"，其他不变。
      console.log(result2);

      // 3）. 抛出错误
      const result3 = p.then(
        (value) => {
          console.log(value);
          // throw new Error("出错啦！");
          // 或者
          throw "出错啦!";
        },
        (reason) => {}
      );
      // 控制台输出：[[PromiseState]]: "rejected"，[[PromiseResult]]: Error: "出错啦！"，其他不变。
      console.log(result3);

      // --------------------- 链式调用方式 ---------------------
      const result4 = p
        .then(
          (value) => {
            return "最外层成功回调函数！";
          },
          (reason) => {
            return "最外层失败回调函数！";
          }
        )
        .then(
          (value) => {
            console.log(value);
            return "最内层层成功回调函数！";
          },
          (reason) => {
            console.log(reason);
            return "最内层失败回调函数！";
          }
        );
      console.log(result4);

      // 总结：
      // Promise回调函数的成功或者失败状态为"fulfilled"；默认返回值为：undefined；除此之外，Promise还支持链式回调。
      // 1. 如果回调函数中返回的结果是 非 promise 类型的属性, 状态为成功, 返回值为对象的成功的值；
      // 2. 如果回调函数中返回的结果是 promise 类型的属性, 状态为成功, 返回内层回调函数成功的值；状态为失败, 返回内层回调函数失败的值；
      // 3. 如果回调函数中返回的结果是 手动抛出的错误或者异常，返回值为对象的失败的值。
    </script>
  </body>
</html>
